config/routes.rb
Rails.application.routes.draw do

  resources :exports

  get 'incomes/index'

  get 'incomes/new'

  get 'salaries/index'

  get 'salaries/new'

  get 'expenses/index'

  get 'expenses/new'

  get 'payments/new'

  get 'payments/index'

  get 'customers/new'

  get 'customers/index'

  get 'new/index'

  get 'invoices/new'

  get 'invoices/index'

  get 'items/index'

  get 'items/new'

  get 'students/upload'

  get 'students/payment'

  get 'home/reports'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :students do
    collection { post :import }
    collection do
      post "pay"
      get "validate_model"
      get "validate_rollnum"
    end
  end

  resources :grades do
    member do
      get "addFeeToClass"
    end
    collection do
      get "validateClassTitle"
    end
  end

  resources :items do
    collection do
      get 'validateItemCode'
      post 'adding'
      get 'addStock'
      get 'export'
      get 'report'
    end
  end

  resources :invoices do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      get 'getCredit'
      get 'report'
    end
  end

  resources :sales do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      
    end
  end
  
  resources :bills do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
    member do
      get 'editExport'
      patch 'updateExport'
    end
  end

  resources :customers
  resources :payments
  resources :expenses
  resources :employees do
    member do
      get 'loan'
      
    end
    collection do
      post 'payLoan'
    end
  end
  resources :salaries
  resources :incomes

  resources :lines do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :invoice
	belongs_to :item
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :invoices
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :salaries
end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/models/export.rb
class Export < ActiveRecord::Base
end

app/models/fund.rb
class Fund < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :students
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :bills
	belongs_to :customer
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates_uniqueness_of :title
	has_many :bills
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :sale
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/salary.rb
class Salary < ActiveRecord::Base
	belongs_to :employee
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	has_many :lines
end

app/models/student.rb
class Student < ActiveRecord::Base
	
	validates_uniqueness_of :email
	belongs_to :grade	
	
	def self.import(file)
		begin
		  CSV.foreach(file.path, headers: true) do |row|
		    student = find_by_id(row["id"]) || new
		    student.attributes = row.to_hash.slice(*row.to_hash.keys)
		    student.date=nil
		    student.paid=0
		    student.save!
		  end
		rescue => e
	        # Rails.logger.error { "Encountered an error" }
      		"notok"
      	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.where.not(status: 'delete')
	end

	def new
		@employee = Employee.new
	end

	def create
		emp = Employee.new(create_params)
		emp.loan = 0
		emp.status = 'active'
		if emp.save
			redirect_to employees_path, :notice => 'Employee Added Successfully'
		end
	end

	def edit
		@employee = Employee.find(params[:id])
	end

	def loan
		@employee = Employee.find(params[:id])
	end

	def update
		emp = Employee.find(params[:id])
	    if emp.update(create_params)
	      redirect_to employees_path, :notice => 'Information Updated successfully!'
	    else
	      redirect_to :back, :alert => 'Could not update information!'
	    end
	end

	def destroy
	    emp = Employee.find(params[:id])
	    emp.status = 'delete'
	    emp.save
	    redirect_to employees_path, :notice => 'Item Deleted!'
	end

	private
		def create_params
			params.require(:employee).permit(:name, :contact, :address_home, :salary_type, :salary, :iqama, :expire_iqama, :loan, :status)
		end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/employees/edit.html.erb
<script type="text/javascript">
  var d = document.getElementById("employees");
d.className = d.className + " active";
</script>


<%= form_for @employee do |emp| %>
	<h2>Add Employee</h2>
	<div class="col-md-6">

		<div class="form-group">
			<label>Full Name</label>
			<%= emp.text_field :name , :style => 'width:70%;height:34px;', class: 'form-control', required: true, autofocus: true %>
			<!-- <div class = "hide" id= "error_div">
				<span style = "color:red;" id="error_text">  </span>
			</div> -->
		</div>

		<div class="form-group">
			<label>Iqama Number</label>
			<%= emp.text_field :iqama, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<label>Iqama Expiration Date</label>
			<%= emp.text_field :expire_iqama, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<label>Contact</label>
			<%= emp.text_field :contact, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

	</div>
	<div class="col-md-6">

		
		<div class="form-group">
			<label>Date</label>
			<input style = 'width:70%;height:34px;'  class = 'form-control' value = '<%=DateTime.now.strftime('%a, %B %e, %Y')%>' disabled >
		</div>
		
		<div class="form-group">
			<label>Salary</label>
			<%= emp.text_field :salary, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<label>Address(Home Country)</label>
			<%= emp.text_field :address_home, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>
		<br>
		<div class="size-bock">
			<span >Salary Type 	</span>
			<br>
			<div class="row size-bock-row">
				<div class="col-xs-6 col-md-6">
				 	<div class="form-group">
						<div class="col-sm-9">
							<%= emp.radio_button :salary_type, 'Monthly', :checked => true %> Monthly
						</div>
					</div>
				</div>
			  	<div class="col-xs-6 col-md-6">
			  		<div class="form-group">
						<div class="col-sm-9">
							<%= emp.radio_button :salary_type, 'Weekly'%> Weekly
						</div>
					</div>
				</div>
			</div>
			<%= emp.submit "Update Information", :class => 'btn-create btn btn-success' %>
		</div>
	</div>
<% end %>

app/views/employees/index.html.erb
<script type="text/javascript">
  var d = document.getElementById("employees");
d.className = d.className + " active";
  $(document).ready(function() {

    var table = $('#example').dataTable({
        "order": [[0, "asc"]],
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard"
                },
                {
                    "sExtends": "csv",
                    "sButtonText": "Save to CSV"
                }
            ]
        },
        /////////////////////////////////////////////
        <% if @employees.count > 0 %>
            "footerCallback": function ( row, data, start, end, display ) {
              var api = this.api(), data;
   
              // Remove the formatting to get integer data for summation
              var intVal = function ( i ) {
                  return typeof i === 'string' ?
                      i.replace(/[\$,]/g, '')*1 :
                      typeof i === 'number' ?
                          i : 0;
              };
              // Total over this page
              pageTotal = api
                  .column( 5, { page: 'current'} )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  }, 0 );
   
              // Update footer
              $('#pgamount').text('Total: '+ pageTotal);
          }
        <% end %>
    });
  });

</script>

<h2>Employees 
<div style = "float: right;font-size: 14px;border-radius: 10px;padding: 5px;background-color: white;margin-bottom:10px;">
  <strong> <span id = 'totalamount' style = "color: Blue;margin-right : 40px; margin-left: 20px;">   Monthly Salaries : <%= Employee.where(salary_type: 'Monthly', status: 'active').sum('salary') %> </span></strong>
  <strong> <span id = 'totalamount' style = "color: Blue;margin-right : 40px; margin-left: 20px;">   Weekly Salaries : <%= Employee.where(salary_type: 'Weekly', status: 'active').sum('salary') %> </span></strong>
  <strong> <span  style = "color: Blue;margin-right : 40px; margin-left: 20px;">  Total Employees : <%= @employees.count %> </span></strong>
  <strong> <span  style = "color: Blue;margin-right : 40px; margin-left: 20px;">  Total Loan : <%= @employees.sum('loan') %> </span></strong>
</div>
<br>
<br>
<div style="float:right">
  <a href="<%= new_employee_path %>" class="btn btn-info pull-right" style="width:200px;"> Add an Employee</a>
</div>
<br>
</h2>
<table id="example" class="display">
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Mobile Number</th>
      <th>Address Pakistan</th>
      <th>Iqama Number</th>
      <th>Iqama Expiry</th>
      <th>Salary</th>
      <th>Salary Type</th>
      <th>Loan</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.try(:each) do |emp| %>
      <tr class ="<%= emp.id %>">
        <td>
          <%= link_to emp.name, edit_employee_path(emp.id) %>
        </td>
        <td>
          <%= emp.contact %>
        </td>
        <td>
          <%= emp.address_home %>
        </td>
        <td>
          <%= emp.iqama %>
        </td>
        <td>
          <%= emp.expire_iqama %>
        </td>
        <td>
          <%= emp.salary %>
        </td>
        <td>
          <%= emp.salary_type %>
        </td>
        <td>
          <%= emp.loan %>
        </td>
        <td>
          <%= link_to 'Pay Salalry', new_salary_path(emp.id), class: 'btn btn-info', style: 'width:100%'%>
          <%= link_to 'Pay Loan', loan_employee_path(emp.id), class: 'btn btn-default', style: 'width:100%' %>
          <%= link_to 'Edit', edit_employee_path(emp.id), class: 'btn btn-default', style: 'width:100%' %>
          <%= link_to 'Delete', employee_path(emp.id), method: 'delete' , class: 'btn btn-danger', style: 'width:100%' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style = "float:right; font-size: 14px">
  <strong> <span id = 'pgamount' > </span></strong><br>
</div>

app/views/employees/loan.html.erb
<script type="text/javascript">
  var d = document.getElementById("employees");
d.className = d.className + " active";
</script>


<%= form_for @employee do |emp| %>
	<h2>Pay Loan</h2>
	<br>
	<%= emp.hidden_field :id %>
	<div class="col-md-6">
		<div class="form-group">
			<label>Full Name</label>
			<%= emp.text_field :name , :style => 'width:70%;height:34px;', class: 'form-control', required: true, disabled: true %>
			<!-- <div class = "hide" id= "error_div">
				<span style = "color:red;" id="error_text">  </span>
			</div> -->
		</div>

		<div class="form-group">
			<label>Iqama Number</label>
			<%= emp.text_field :iqama, :style => 'width:70%;height:34px;', class: 'form-control', disabled: true %>
		</div>

		<div class="form-group">
			<label>Iqama Expiration Date</label>
			<%= emp.text_field :expire_iqama, :style => 'width:70%;height:34px;', class: 'form-control', disabled: true %>
		</div>

		<div class="form-group">
			<label>Contact</label>
			<%= emp.text_field :contact, :style => 'width:70%;height:34px;', class: 'form-control', disabled: true%>
		</div>

		<div class="form-group">
			<label>Loan Amount</label>
			<%= emp.text_field :loan, :style => 'width:70%;height:34px;', class: 'form-control'%>
		</div>

	</div>
	<div class="col-md-6">

		
		<div class="form-group">
			<label>Date</label>
			<input style = 'width:70%;height:34px;'  class = 'form-control' value = '<%=DateTime.now.strftime('%a, %B %e, %Y')%>' disabled >
		</div>
		
		<div class="form-group">
			<label>Salary</label>
			<%= emp.text_field :salary, :style => 'width:70%;height:34px;', class: 'form-control', disabled: true %>
		</div>

		<div class="form-group">
			<label>Address(Home Country)</label>
			<%= emp.text_field :address_home, :style => 'width:70%;height:34px;', class: 'form-control', disabled: true %>
		</div>
		<br>
		<div class="size-bock">
			<span >Salary Type 	</span>
			<br>
			<div class="row size-bock-row">
				<div class="col-xs-6 col-md-6">
				 	<div class="form-group">
						<div class="col-sm-9">
							<%= emp.radio_button :salary_type, 'Monthly', :checked => true, disabled: true %> Monthly
						</div>
					</div>
				</div>
			  	<div class="col-xs-6 col-md-6">
			  		<div class="form-group">
						<div class="col-sm-9">
							<%= emp.radio_button :salary_type, 'Weekly', disabled: true%> Weekly
						</div>
					</div>
				</div>
			</div>
			<%= emp.submit "Pay Loan", :class => 'btn-create btn btn-success' %>
		</div>
	</div>
<% end %>

app/views/employees/new.html.erb
<script type="text/javascript">
  var d = document.getElementById("employees");
d.className = d.className + " active";
</script>


<%= form_for @employee do |emp| %>
	<h2>Add Employee </h2>
	<div class="col-md-6">

		<div class="form-group">
			<label>Full Name</label>
			<%= emp.text_field :name , :style => 'width:70%;height:34px;', class: 'form-control', required: true, autofocus: true %>
			<!-- <div class = "hide" id= "error_div">
				<span style = "color:red;" id="error_text">  </span>
			</div> -->
		</div>

		<div class="form-group">
			<label>Iqama Number</label>
			<%= emp.text_field :iqama, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<label>Iqama Expiration Date</label>
			<%= emp.text_field :expire_iqama, as: :bootstrap_datepicker, :style => 'width:70%;height:34px;', class: 'form-control datepicker' %>
		</div>

		<div class="form-group">
			<label>Contact</label>
			<%= emp.text_field :contact, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

	</div>
	<div class="col-md-6">

		
		<div class="form-group">
			<label>Date</label>
			<input style = 'width:70%;height:34px;'  class = 'form-control' value = '<%=DateTime.now.strftime('%a, %B %e, %Y')%>' disabled >
		</div>
		
		<div class="form-group">
			<label>Salary</label>
			<%= emp.text_field :salary, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<label>Address(Home Country)</label>
			<%= emp.text_field :address_home, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>
		<br>
		<div class="size-bock">
			<span >Salary Type 	</span>
			<br>
			<div class="row size-bock-row">
				<div class="col-xs-6 col-md-6">
				 	<div class="form-group">
						<div class="col-sm-9">
							<%= emp.radio_button :salary_type, 'Monthly', :checked => true %> Monthly
						</div>
					</div>
				</div>
			  	<div class="col-xs-6 col-md-6">
			  		<div class="form-group">
						<div class="col-sm-9">
							<%= emp.radio_button :salary_type, 'Weekly'%> Weekly
						</div>
					</div>
				</div>
			</div>
			<%= emp.submit "Add Employee", :class => 'btn-create btn btn-success' %>
		</div>
	</div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>