config/routes.rb
Rails.application.routes.draw do

  resources :exports

  get 'incomes/index'

  get 'incomes/new'

  get 'salaries/index'

  get 'salaries/new'

  get 'expenses/index'

  get 'expenses/new'

  get 'payments/new'

  get 'payments/index'

  get 'customers/new'

  get 'customers/index'

  get 'new/index'

  get 'invoices/new'

  get 'invoices/index'

  get 'items/index'

  get 'items/new'

  get 'students/upload'

  get 'students/payment'

  get 'home/reports'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :students do
    collection { post :import }
    collection do
      post "pay"
      get "validate_model"
      get "validate_rollnum"
    end
  end

  resources :grades do
    member do
      get "addFeeToClass"
    end
    collection do
      get "validateClassTitle"
    end
  end

  resources :items do
    collection do
      get 'validateItemCode'
      post 'adding'
      get 'addStock'
      get 'export'
      get 'report'
    end
  end

  resources :invoices do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      get 'getCredit'
      get 'report'
    end
  end

  resources :sales do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      
    end
  end
  
  resources :bills do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
    member do
      get 'editExport'
      patch 'updateExport'
    end
  end

  resources :customers
  resources :payments
  resources :expenses
  resources :employees do
    member do
      get 'loan'
      
    end
    collection do
      post 'payLoan'
    end
  end
  resources :salaries
  resources :incomes

  resources :lines do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :invoice
	belongs_to :item
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :invoices
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :salaries
end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/models/export.rb
class Export < ActiveRecord::Base
end

app/models/fund.rb
class Fund < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :students
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :bills
	belongs_to :customer
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates_uniqueness_of :title
	has_many :bills
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :sale
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/salary.rb
class Salary < ActiveRecord::Base
	belongs_to :employee
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	has_many :lines
end

app/models/student.rb
class Student < ActiveRecord::Base
	
	validates_uniqueness_of :email
	belongs_to :grade	
	
	def self.import(file)
		begin
		  CSV.foreach(file.path, headers: true) do |row|
		    student = find_by_id(row["id"]) || new
		    student.attributes = row.to_hash.slice(*row.to_hash.keys)
		    student.date=nil
		    student.paid=0
		    student.save!
		  end
		rescue => e
	        # Rails.logger.error { "Encountered an error" }
      		"notok"
      	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!

  ####### System admin is 0
  ####### School admin is 1
  ####### exams is 2
  ####### accounts is 3
  def index
  	if current_user && current_user.user_type == 1 || current_user.user_type == 0
  		@students = Student.where('staus !=?', 'delete')
  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def new
    @student = Student.new
  end

  def create
    # return render json: params.inspect
    @student = Grade.find(params[:student][:grade_id]).students.create(create_params)
    if @student.save!
      @student.amount = Grade.find(params[:student][:grade_id]).fee
      @student.staus = ''
      @student.save!
      User.create!(email: @student.email, password: "school", user_type: 4, password_confirmation: "school")
      redirect_to students_path, :notice => 'Student added successfully!'
    else
      redirect_to :back, :alert => "Fill the form again!"
    end
  end

  def show
  	if current_user && current_user.user_type == 1 || current_user.user_type == 0
      @student = Student.find(params[:id])

  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def upload
  	if current_user && current_user.user_type == 1 || current_user.user_type == 0

  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(create_params)
      redirect_to student_path(@student.id), :notice => 'Information Updated successfully!'
    else
      redirect_to student_path(@student.id), :alert => 'Could not update information!'
    end
  end

  def destroy
    student = Student.find(params[:id])
    student.staus = 'delete'
    student.save!
    user = User.find_by_email(student.email)
    user.delete
    redirect_to students_path, :notice => 'Student deleted!'
  end

  def import
    if current_user && current_user.user_type == 2 || current_user.user_type == 0
  	  result = Student.import(params[:file])
      if result=="notok"
        redirect_to students_upload_path, :alert => "Error in file."
      else
  	    redirect_to students_upload_path, :notice => "Students imported."
      end
    else
      redirect_to authenticated_root_path, :alert => 'Access Denied!'
    end
  end

  def payment
  	if current_user && current_user.user_type == 3
      @students = Student.where('staus !=?', 'delete')
      @std = Student.new
  	else
  		redirect_to authenticated_root_path, :alert => 'Access Denied!'
  	end
  end

  def pay
    if current_user && current_user.user_type == 3
      @std = Student.find(params[:student][:id])
      # return render json: @std
      @std.paid = @std.paid.to_i + params[:student][:paid].to_i
      @std.date = params[:student][:date]
      @std.save!
      redirect_to students_payment_path, :success => 'Payment Updated!'
    else
      redirect_to authenticated_root_path, :alert => 'Access Denied!'
    end
  end

  def validate_model
    user = User.find_by_email(params[:email])
    value = user.present?
    respond_to do |format|
      format.json {render json: value}
    end
  end

  def validate_rollnum
    user = Grade.find(params[:grade]).students.find_by_rollnum(params[:roll_Number]);
    value = user.present?
    respond_to do |format|
      format.json {render json: value}
    end
  end

  private
    def create_params
      params.require(:student).permit(:name, :sirname, :contact, :address, :email, :grade_id, :dob, :status, :rollnum ,:gender)      
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<script type="text/javascript">
	var d = document.getElementById("std");
d.className = d.className + " active";
</script>

<h2>Edit Student Record</h2>
</br>
<div class="col-md-3"></div>
<div class="col-md-9">
	<%= form_for @student, method: :put do |std| %>
		<div class="form-group">
			<%= std.label :name %>
			<%= std.text_field :name , :style => 'width:70%;height:34px;',  class: 'form-control', required: true, autofocus: true %>
		</div>

		<div class="form-group">
			<%= std.label :father_name %>
			<%= std.text_field :sirname , :style => 'width:70%;height:34px;', class: 'form-control', required: true %>
		</div>

		<!-- <div class="form-group">
			<%#= std.label :grade %>
		    <%#= std.collection_select :grade_id, Grade.order(:title),:id,:title , {}, {class: "form-control", style: 'width:70%;', :id => 'grade'} %>
		</div> -->

		<!-- <div class="form-group">
			<%#= std.label :roll_Number %>
		    <%#= std.text_field :rollnum , :id => 'roll_Number' ,:style => 'width:70%;height:34px;', class: 'form-control', required: true %>

		    <div class = "hide" id= "error_div_rollnum">
				<span style = "color:red;" id="error_text_rollnum">  </span>
			</div>
		</div> -->
		
		<div class="form-group">
			<%= std.label :contact %>
			<%= std.text_field :contact , :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= std.label :date_of_Birth %>
			<%= std.text_field :dob , :id => 'datepicker', :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class = 'form-group'>
		    <%= std.label :gender %>
			<%= std.select :gender, options_for_select(%w[MALE FEMALE]),{}, {class: "form-control", style: 'width:70%;'} %>
		</div>

		<!-- <div class="form-group">
			<%#= std.label :email %>
			<%#= std.email_field :email , :id => 'email_field' , :style => 'width:70%;height:34px;', class: 'form-control', required: true %>
			<div class = "hide" id= "error_div">
				<span style = "color:red;" id="error_text">  </span>
			</div>
		</div> -->

		<div class="form-group">
			<%= std.label :address %>
			<%= std.text_area :address , :style => 'width:70%;', rows: 3, class: 'form-control' %>
		</div>
		</br>
		<div class="form-group">
			<%= std.submit :class => 'btn btn-block btn-success form-control', :style => 'width:70%' %>
		</div>
		
	<% end %>
</div>

<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
</script>

app/views/students/index.html.erb
<script type="text/javascript">
  var d = document.getElementById("std");
d.className = d.className + " active";
  $(document).ready(function() {
  

    $('#example').dataTable({
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard"
                },
                {
                    "sExtends": "csv",
                    "sButtonText": "Save to CSV"
                }
            ]

        }
    });
  });

</script>

<h2>Students<a href="<%= new_student_path %>" class="btn btn-info pull-right" style="width:200px;">Admit a new Student</a></h2>
    <table id="example" class="display">
      <thead>
        <tr>
          <th>Roll Number</th>
          <th>Name</th>
          <th>Father Name</th>
          <th>Email</th>
          <th>Garde</th>
          <th>Amount</th>
          <th>Paid</th>
          <th>Remaining</th>
          <th>Date</th>
        </tr>
      </thead>
      <tbody>
        <% @students.try(:each) do |student| %>
          <tr>
            <td>
              <%= student.rollnum %>
            </td>
            <td>
              <%= link_to student.name, student_path(student.id) %>
            </td>
            <td>
              <%= student.sirname %>
            </td>
            <td>
              <%= student.email %>
            </td>
            <td>
              <%= Grade.find(student.grade_id).title %>
            </td>
            <td>
              <%= student.amount %>
            </td>
            <td>
              <%= student.paid %>
            </td>
            <td>
              <%= student.amount-student.paid %>
            </td>
            <td>
              <%= student.date %>
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/students/new.html.erb
<script type="text/javascript">
	var d = document.getElementById("std");
d.className = d.className + " active";
</script>

<h2>Admit a New Student</h2>
</br>
<div class="col-md-3"></div>
<div class="col-md-9">
	<%= form_for @student do |std| %>
		<div class="form-group">
			<%= std.label :name %>
			<%= std.text_field :name , :style => 'width:70%;height:34px;',  class: 'form-control', required: true, autofocus: true %>
		</div>

		<div class="form-group">
			<%= std.label :father_name %>
			<%= std.text_field :sirname , :style => 'width:70%;height:34px;', class: 'form-control', required: true %>
		</div>

		<div class="form-group">
			<%= std.label :grade %>
		    <%= std.collection_select :grade_id, Grade.order(:title),:id,:title , {}, {class: "form-control", style: 'width:70%;', :id => 'grade'} %>
		</div>

		<div class="form-group">
			<%= std.label :roll_Number %>
		    <%= std.text_field :rollnum , :id => 'roll_Number' ,:style => 'width:70%;height:34px;', class: 'form-control', required: true %>

		    <div class = "hide" id= "error_div_rollnum">
				<span style = "color:red;" id="error_text_rollnum">  </span>
			</div>
		</div>
		
		<div class="form-group">
			<%= std.label :contact %>
			<%= std.text_field :contact , :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= std.label :date_of_Birth %>
			<%= std.text_field :dob , :id => 'datepicker', :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class = 'form-group'>
		    <%= std.label :gender %>
			<%= std.select :gender, options_for_select(%w[MALE FEMALE]),{}, {class: "form-control", style: 'width:70%;'} %>
		</div>

		<div class="form-group">
			<%= std.label :email %>
			<%= std.email_field :email , :id => 'email_field' , :style => 'width:70%;height:34px;', class: 'form-control', required: true %>
			<div class = "hide" id= "error_div">
				<span style = "color:red;" id="error_text">  </span>
			</div>
		</div>

		<div class="form-group">
			<%= std.label :address %>
			<%= std.text_area :address , :style => 'width:70%;', rows: 3, class: 'form-control' %>
		</div>
		</br>
		<div class="form-group">
			<%= std.submit :class => 'btn btn-block btn-success form-control', :style => 'width:70%' %>
		</div>
		
	<% end %>
</div>

<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
    $("#email_field").blur(function(){
	  	$.get('/students/validate_model', {email: this.value})
  		.done(function(data){
	  		if (data)
	  		{
	  			$("#error_div").removeClass('hide');
	  			$("#error_text").html($("#email_field").val() + " email already registered!");
	  			$("#email_field").val('');
	  		}
	  		else
	  		{
	  			$("#error_div").addClass('hide');
	  		}
	  	})
	});

  	$("#roll_Number").blur(function(){
  		var grade = $("#grade").val();
	  	$.get('/students/validate_rollnum', {roll_Number: this.value, grade: grade})
  		.done(function(data){
	  		if (data)
	  		{
	  			$("#error_div_rollnum").removeClass('hide');
	  			$("#error_text_rollnum").html($("#roll_Number").val() + " roll number already registered!");
	  			$("#roll_Number").val('');
	  		}
	  		else
	  		{
	  			$("#error_div_rollnum").addClass('hide');
	  		}
	  	});
	});
	$("#grade").change(function(){
  		$("#roll_Number").val('');
	});
</script>

app/views/students/payment.html.erb
<script type="text/javascript">
  var d = document.getElementById("pay");
d.className = d.className + " active";

  $(document).ready(function() {
  

    $('#stdata').dataTable();
  });

</script>

<h2>Students</h2>
    <table id="stdata" class="display">
      <thead>
        <tr>
          <th>Roll Number</th>
          <th>Name</th>
          <th>Father Name</th>
          <th>Garde</th>
          <th>Amount</th>
          <th>Paid</th>
          <th>Remaining</th>
          <th>Date</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @students.try(:each) do |student| %>
          <tr>
            <td>
              <%= student.rollnum %>
            </td>
            <td>
              <%= student.name %>
            </td>
            <td>
              <%= student.sirname %>
            </td>
            <td>
              <%= Grade.find(student.grade_id).title %>
            </td>
            <td>
              <%= student.amount %>
            </td>
            <td>
              <%= student.paid %>
            </td>
            <td>
              <%= student.amount-student.paid %>
            </td>
            <td>
              <%= student.date %>
            </td>
            <td>
            	<div class="input-group" style="width:150px;">
			      <%= form_for @std ,:url => pay_students_path, method: :post do |f| %>
				      <%= f.number_field :paid, :class => 'form-control', :style => 'height:26px;width:100px;', :value => student.amount-student.paid,  in: 0..1000000 %>
				      <%= f.hidden_field :date, :value => DateTime.now %>
				      <%= f.hidden_field :id, :value => student.id %>
				      <!-- <input type="text" class="form-control" style="height:26px;"> -->
				      <span class="input-group-btn">
				        <button type="submit" class="btn btn-small btn-warning" type="button">Pay!</button>
				      </span>
				     <% end %>
			    </div><!-- /input-group -->
            </td>
            
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/students/show.html.erb
<script type="text/javascript">
	var d = document.getElementById("std");
d.className = d.className + " active";
</script>


<div class="table-responsive" style="background-color:white;padding:15px;border-radius:5px;">
	<h2><%= @student.name%></h2>
	</br>

	<table class="table table-striped">
		<tr>
			<td>Name</td> <td><%= @student.name%></td>
		</tr>
		
		<tr>
			<td>Roll Number</td> <td><%= @student.rollnum%></td>
		</tr>

		<tr>
			<td>Father Name</td> <td><%= @student.sirname%></td>
		</tr>

		<tr>
			<td>Grade</td> <td><%= Grade.find(@student.grade_id).title %></td>
		</tr>

		<tr>
			<td>Gender</td> <td><%=@student.gender%></td>
		</tr>

		<tr>
			<td>Date Of Birth</td> <td><%= @student.dob%></td>
		</tr>

		<tr>
			<td>email</td> <td><%= @student.email%></td>
		</tr>

		<tr>
			<td>Contact</td> <td><%= @student.contact%></td>
		</tr>

		<tr>
			<td>Address</td> <td><%= @student.address%></td>
		</tr>
		<tr>
			<td></td><td> <%= link_to 'Back', students_path, class: 'btn btn-default' %> <%= link_to 'Edit', edit_student_path(@student.id), class: 'btn btn-primary' %> <%= link_to 'Delete', student_path(@student.id), method: :delete, data: { confirm: 'Are you sure to delete this student?' }, class: 'btn btn-danger' %> </td>
		</tr>
		
	</table>
</div>

app/views/students/upload.html.erb
<script type="text/javascript">
  var d = document.getElementById("csv");
d.className = d.className + " active";
</script>
<h4>Upload Students List via <span style="font-style:italic;">CSV</span> File</h4>
<u><strong>First row should be : id, name, branch, grade, amount </strong></u>


<%= form_tag import_students_path, multipart: true do %>
  <%= file_field_tag :file, :accept => 'text/csv' %>
  <%= submit_tag "Import", :class => 'btn' %>
<% end %>