config/routes.rb
Rails.application.routes.draw do

  resources :exports

  get 'incomes/index'

  get 'incomes/new'

  get 'salaries/index'

  get 'salaries/new'

  get 'expenses/index'

  get 'expenses/new'

  get 'payments/new'

  get 'payments/index'

  get 'customers/new'

  get 'customers/index'

  get 'new/index'

  get 'invoices/new'

  get 'invoices/index'

  get 'items/index'

  get 'items/new'

  get 'students/upload'

  get 'students/payment'

  get 'home/reports'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :students do
    collection { post :import }
    collection do
      post "pay"
      get "validate_model"
      get "validate_rollnum"
    end
  end

  resources :grades do
    member do
      get "addFeeToClass"
    end
    collection do
      get "validateClassTitle"
    end
  end

  resources :items do
    collection do
      get 'validateItemCode'
      post 'adding'
      get 'addStock'
      get 'export'
      get 'report'
    end
  end

  resources :invoices do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      get 'getCredit'
      get 'report'
    end
  end

  resources :sales do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      
    end
  end
  
  resources :bills do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
    member do
      get 'editExport'
      patch 'updateExport'
    end
  end

  resources :customers
  resources :payments
  resources :expenses
  resources :employees do
    member do
      get 'loan'
      
    end
    collection do
      post 'payLoan'
    end
  end
  resources :salaries
  resources :incomes

  resources :lines do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :invoice
	belongs_to :item
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :invoices
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :salaries
end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/models/export.rb
class Export < ActiveRecord::Base
end

app/models/fund.rb
class Fund < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :students
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :bills
	belongs_to :customer
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates_uniqueness_of :title
	has_many :bills
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :sale
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/salary.rb
class Salary < ActiveRecord::Base
	belongs_to :employee
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	has_many :lines
end

app/models/student.rb
class Student < ActiveRecord::Base
	
	validates_uniqueness_of :email
	belongs_to :grade	
	
	def self.import(file)
		begin
		  CSV.foreach(file.path, headers: true) do |row|
		    student = find_by_id(row["id"]) || new
		    student.attributes = row.to_hash.slice(*row.to_hash.keys)
		    student.date=nil
		    student.paid=0
		    student.save!
		  end
		rescue => e
	        # Rails.logger.error { "Encountered an error" }
      		"notok"
      	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  	@payment = Payment.new
    @credit = Customer.where.not(status: 'delete').order(:name).first.credit
  end

  def create
  	# return render json: params
  	@payment = Payment.new(create_params)
  	customer = Customer.find(params[:payment][:customer_id])
  	customer.credit = customer.credit - @payment.total
  	customer.paid = customer.paid + @payment.total
  	customer.save
    fund = Fund.first
    fund.amount = fund.amount - @payment.total
    fund.save	
  	if @payment.save
  		redirect_to payment_path(@payment.id)
  	end
  end

  def index
  	@payments = Payment.all
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    pay = Payment.find(params[:id])
    cust = Customer.find(pay.customer_id)
    cust.paid = cust.paid - pay.total
    cust.credit = cust.credit + pay.total
    f = Fund.first
    f.amount = f.amount + pay.total
    pay.total = params[:payment][:total]
    pay.save
    f.amount = f.amount - pay.total
    f.save
    cust.paid = cust.paid + pay.total
    cust.credit = cust.credit - pay.total
    cust.save
    redirect_to payments_path
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def destroy
    pay = Payment.find(params[:id])
    cust = Customer.find(pay.customer_id)
    cust.paid = cust.paid - pay.total
    cust.credit = cust.credit + pay.total
    cust.save
    pay.destroy
    redirect_to payments_path
  end

    private
	    def create_params
	      params.require(:payment).permit(:customer_id, :total, :remarks, :created_at)      
	    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<script type="text/javascript">
  var d = document.getElementById("payments");
  d.className = d.className + " active";
</script>

<h2>Edit Payment</h2>
</br>
<div class="col-md-3"></div>
<div class="col-md-9">
	<%= form_for @payment do |pay| %>
		<div class="form-group">
			<label>Date</label>
			<input style = 'width:70%;height:34px;'  class = 'form-control' value = '<%=@payment.created_at.strftime('%a, %B %e, %Y')%>' disabled >
			<br>
			<label> Company/Party  </label>
			<%= pay.collection_select :customer_id, Customer.order(:name),:id,:name , {}, {class: "form-control", style: 'width:70%;', disabled: true} %>
		</div>

		<div class="form-group">
			<%= pay.label :Amount %>
			<%= pay.text_field :total , :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= pay.label :ramarks %>
			<%= pay.text_field :remarks , :style => 'width:70%;height:34px;', class: 'form-control', disabled: true%>
		</div>

		<div class="form-group">
			<%= pay.submit :class => 'btn btn-block btn-success form-control', :style => 'width:70%' %>
		</div>

	<% end %>
</div>

app/views/payments/index.html.erb
<script type="text/javascript">
  var d = document.getElementById("payments");
  d.className = d.className + " active";
  $(document).ready(function() {
    $('#example').dataTable({
        "order": [[0, "desc"]],
        dom: 'T<"clear">lfrtip',
        tableTools: {
          "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
          "aButtons": [
            {
              "sExtends": "copy",
              "sButtonText": "Copy to clipboard"
            },
            {
              "sExtends": "csv",
              "sButtonText": "Save to CSV"
            }
          ]
        },
        <% if @payments.count > 0 %>
            "footerCallback": function ( row, data, start, end, display ) {
              var api = this.api(), data;
   
              // Remove the formatting to get integer data for summation
              var intVal = function ( i ) {
                  return typeof i === 'string' ?
                      i.replace(/[\$,]/g, '')*1 :
                      typeof i === 'number' ?
                          i : 0;
              };
   
              // Total over all pages
              total = api
                  .column( 2 )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  } );
              $('#totalpaid').text('Total Payments: '+total+ ' SAR');
              // Total over this page
              pageTotal = api
                  .column( 2, { page: 'current'} )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  }, 0 );
   
              // Update footer
              $('#pgamount').text('Total: '+ pageTotal);
          }
        <% end %>
    });
  });

</script>

<h2>Payments <a href="<%= payments_new_path %>" class="btn btn-info pull-right" style="width:200px;"> Pay Cash</a></h2>
<span id="totalpaid" style="background : #0040FF; border-radius: 10px;padding: 10px;color: white;margin-left: 35%;">Total Paid: 0 SAR</span>
<table id="example" class="display">
  <thead>
    <tr>
      <th>Date</th>
      <th>Company/Party</th>
      <th>Amount</th>
      <th>Remarks</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @payments.try(:each) do |pay| %>
      <tr>
        <td>
          <%= pay.created_at.strftime('%a, %B %e, %Y') %>
        </td>
        <td>
          <%= Customer.find(pay.customer_id).name %>
        </td>
        <td>
        	<%= pay.total %>
        </td>
        <td>
          <%= pay.remarks %>
        </td>
        <td>
          <%= link_to 'Edit', edit_payment_path(pay.id) , class: 'btn btn-default'%>
              <%= link_to 'Delete', payment_path(pay.id), method: 'delete' , class: 'btn btn-danger'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style = "float:right; font-size: 14px">
  <strong> <span id = 'pgamount' > </span></strong><br>
</div>

app/views/payments/new.html.erb
<script type="text/javascript">
  var d = document.getElementById("payments");
  d.className = d.className + " active";
</script>

<h2>Issue Payment</h2>
</br>
<div class="col-md-3"></div>
<div class="col-md-9">
	<%= form_for @payment do |pay| %>
		<div class="form-group">
			<label>Date</label>
			<%= pay.text_field :created_at, id: 'datepicker' , :style => 'width:70%;height:34px;', class: 'form-control' %>
			<br>
			<label> Company/Party  </label>
			<%= pay.collection_select :customer_id, Customer.where.not(status: 'delete').order(:name),:id,:name , {}, {class: "form-control", style: 'width:70%;'} %>
			<div>
				<span id = "credits" style = "color: red">Credit: <%= @credit %></span>
			</div>
		</div>

		<div class="form-group">
			<%= pay.label :Amount %>
			<%= pay.text_field :total , :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= pay.label :ramarks %>
			<%= pay.text_field :remarks , :style => 'width:70%;height:34px;', class: 'form-control'%>
		</div>

		<div class="form-group">
			<%= pay.submit :class => 'btn btn-block btn-success form-control', :style => 'width:70%' %>
		</div>

	<% end %>
</div>

<script type="text/javascript">
	$( "#datepicker" ).datepicker({format: 'yyyy-mm-dd'} );

	$( "#payment_customer_id" ).change(function() {
	  $.get('/invoices/getCredit', {id: $('#payment_customer_id').val()})
	    .done(function(data){
	    	$('#credits').text('Credit: '+ data[0].credit)
	    });
	});
</script>

app/views/payments/show.html.erb
<h2>Payment </h2>
<div style="background-color: white; padding: 40px; border-radius:40px">
  <table class="table">
    <tbody>
      <tr>
        <td>
          <strong>Date</strong>
        </td>
        <td>
          <%= @payment.created_at.strftime('%a, %B %e, %Y') %>
        </td>
      </tr>

      <tr>
        <td>
          <strong>Company/Party</strong>
        </td>
        <td>
          <%= Customer.find(@payment.customer_id).name %>
        </td>
      </tr>

      <tr>
        <td>
          <strong>Amount</strong>
        </td>
        <td>
          <%= @payment.total %>
        </td>
      </tr>

      <tr>
        <td>
          <strong>Remarks</strong>
        </td>
        <td>
          <%= @payment.remarks %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<a href="#" style = " float: right; margin-top:10px; width: 199px" class="btn btn-info btn-lg" onclick="window.print();return false;">Print</a>