config/routes.rb
Rails.application.routes.draw do

  resources :exports

  get 'incomes/index'

  get 'incomes/new'

  get 'salaries/index'

  get 'salaries/new'

  get 'expenses/index'

  get 'expenses/new'

  get 'payments/new'

  get 'payments/index'

  get 'customers/new'

  get 'customers/index'

  get 'new/index'

  get 'invoices/new'

  get 'invoices/index'

  get 'items/index'

  get 'items/new'

  get 'students/upload'

  get 'students/payment'

  get 'home/reports'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :students do
    collection { post :import }
    collection do
      post "pay"
      get "validate_model"
      get "validate_rollnum"
    end
  end

  resources :grades do
    member do
      get "addFeeToClass"
    end
    collection do
      get "validateClassTitle"
    end
  end

  resources :items do
    collection do
      get 'validateItemCode'
      post 'adding'
      get 'addStock'
      get 'export'
      get 'report'
    end
  end

  resources :invoices do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      get 'getCredit'
      get 'report'
    end
  end

  resources :sales do
    member do
      get 'credit'
      get 'cancel'
      get 'customer'
    end
    collection do
      get 'canceled'
      post 'updateInvoice'
      
    end
  end
  
  resources :bills do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
    member do
      get 'editExport'
      patch 'updateExport'
    end
  end

  resources :customers
  resources :payments
  resources :expenses
  resources :employees do
    member do
      get 'loan'
      
    end
    collection do
      post 'payLoan'
    end
  end
  resources :salaries
  resources :incomes

  resources :lines do
    collection do
      post 'createBill'
      get 'getbills'
      get 'removebills'
      get 'validateCode'
    end
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :invoice
	belongs_to :item
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :invoices
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :salaries
end

app/models/expense.rb
class Expense < ActiveRecord::Base
end

app/models/export.rb
class Export < ActiveRecord::Base
end

app/models/fund.rb
class Fund < ActiveRecord::Base
end

app/models/grade.rb
class Grade < ActiveRecord::Base
	has_many :students
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :bills
	belongs_to :customer
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates_uniqueness_of :title
	has_many :bills
end

app/models/line.rb
class Line < ActiveRecord::Base
	belongs_to :sale
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/salary.rb
class Salary < ActiveRecord::Base
	belongs_to :employee
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	has_many :lines
end

app/models/student.rb
class Student < ActiveRecord::Base
	
	validates_uniqueness_of :email
	belongs_to :grade	
	
	def self.import(file)
		begin
		  CSV.foreach(file.path, headers: true) do |row|
		    student = find_by_id(row["id"]) || new
		    student.attributes = row.to_hash.slice(*row.to_hash.keys)
		    student.date=nil
		    student.paid=0
		    student.save!
		  end
		rescue => e
	        # Rails.logger.error { "Encountered an error" }
      		"notok"
      	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
  	if current_user
      @credit = Customer.where.not(status: 'delete').order(:name).first.credit
	  	@invoice = Sale.new
      @autogen = Sale.last.id + 1
	  	@bill = @invoice.lines.new
	  	@bills = @invoice.lines
	else
		redirect_to authenticated_root_path(@autogen), :alert => 'Access Denied!'
	end
  end

  def updateInvoice
    puts 'as'*40
  	invoice = Sale.find(params[:format])
    invoice.status = 'active'
    cust = Customer.find(params[:sale][:customer_id])
    invoice.customerName = cust.name
    if invoice.update(update_params)
      cust.paid = cust.paid + invoice.lines.sum("(gross-tear) * price")
      cust.credit = cust.credit - invoice.lines.sum("(gross-tear) * price")
      cust.save
      invoice.lines.each do |bill|
        item = Item.find(bill.item_id)
        item.left = item.left - (bill.gross - bill.tear)
        item.save
      end
      redirect_to sales_path, :notice => 'Invoice added successfully!'
    else
      redirect_to :back, :alert => 'Could not update information!'
    end
  end

  def index
    @invoices = Sale.where(status: 'active')
    # @total = Bill.where.not(invoice_id: nil).sum('quantity * pirice')
  end

  def credit
  	@invoice = Sale.find(params[:id])
    @autogen = params[:id]
  	@bills = @invoice.lines
  	
  end

  def cancel
    invoice = Sale.find(params[:id])
    invoice.status = 'cancelled'
    bills = invoice.lines
    bills.each do |bill|
      item = Item.find(bill.item_id)
      item.left = item.left + bill.quantity
      item.sold = item.sold - bill.quantity
      item.save!
    end
    invoice.save!
  end

  def destroy
    invoice = Sale.find(params[:id])
    cust = Customer.find(invoice.customer_id)
    cust.credit = cust.credit + invoice.lines.sum('price * (gross-tear)')
    cust.paid = cust.paid - invoice.lines.sum('price * (gross-tear)')
    cust.save
    invoice.lines.each do |bill|
      item = Item.find(bill.item_id)
      item.left = item.left + (bill.gross - bill.tear)
      item.save
    end
    invoice.lines.destroy_all
    invoice.destroy
    Sale.create
    redirect_to sales_path, :alert => 'Invoice Deleted successfully'
  end

  def customer
    # return render json: params
    @customer =  Customer.find(params[:id])
    @invoices = Sale.where(customer_id: @customer.id)
  end

  def canceled
    @invoices = Sale.where.not(bookNum: nil , status: nil)
  end

  private
    def update_params
      params.require(:sale).permit(:id,:bookNum, :customerName,:customer_id, :customerMobile, :right, :left, :paid, :vehicle, :driver, :created_at)      
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/canceled.html.erb
<script type="text/javascript">
  var d = document.getElementById("cancelled");
d.className = d.className + " active";
  $(document).ready(function() {

    var table = $('#example').dataTable({
        "order": [[1, "desc"]],
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard"
                },
                {
                    "sExtends": "csv",
                    "sButtonText": "Save to CSV"
                }
            ]
        }
    });
  });

</script>

<h2>Invoices</h2>
    <table id="example" class="display">
      <thead>
        <tr>
          <th>Date</th>
          <th>Invoice #</th>
          <th>Book Number</th>
          <th>Customer Name</th>
          <th>Customer Mobile</th>
          <th>Total</th>
          <th>Paid</th>
          <th>Credit</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @invoices.try(:each) do |inv| %>
          <tr class ="<%= inv.id %>">
            <td>
              <%= inv.created_at.strftime('%a, %B %e, %Y') %>
            </td>
            <td>
              <%= link_to inv.id, credit_invoice_path(inv.id) %>
            </td>
            <td>
              <%= inv.bookNum %>
            </td>
            <td>
              <%= inv.customerName %>
            </td>
            <td>
              <%= inv.customerMobile %>
            </td>
            <td>
              <%= inv.bills.sum("quantity * price") %>
            </td>
            <td>
              <%= inv.try(:paid) %>
            </td>
            <td>
              <%= inv.bills.sum("quantity * price").to_f - inv.try(:paid).to_f %>
            </td>
            <td>
              <%= inv.status %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/sales/credit.html.erb
<script type="text/javascript">
  var d = document.getElementById("saless");
d.className = d.className + " active";
</script>

<h2>Sales Invoice </h2> <a href="#" style = " float: right;" class="btn btn-info" onclick="window.print();return false;">Print</a>
<br>
<br>
<div style="width:50%;">
	<table class="table">		
		<tbody>
			<tr>
				<th>Invoice ID</th>
				<td> <%= @invoice.id %></td>
			</tr>
			<tr>
				<th>Date</th>
				<td><%= @invoice.created_at.strftime('%a, %B %e, %Y') %></td>
			</tr>
			<tr>
				<th>invoice #</th>
				<td><%= @invoice.bookNum %></td>
			</tr>
			<tr>
				<th>Customer/Party Name</th>
				<td><%= @invoice.customerName %></td>
			</tr>
			<tr>
				<th>Deiver</th>
				<td><%= @invoice.driver %></td>
				
			</tr>
			<tr>
				<th>Vehicle</th>
				<td><%= @invoice.vehicle %></td>
			</tr>		
		</tbody>

	</table>
</div>
<div class = "col-md-12" style="background-color:black; margin-bottom:20px;margin-top:20px;">	
</div>
<div style="padding:10px;border-radius:5px;background-color:white;margin-top:60px; overflow:hidden;">
	<table class="table">
		<thead>
			<th>Quality Name</th>
			<th>Gross Weight(Kg)</th>
			<th>Tear Weight (Kg)</th>
			<th>Net Weight</th>
			<th>Rate</th>
			<th>Total</th>
		</thead>
		<tbody id = 'billtable'>
			<% @bills.each do |bill| %>
				<tr>
					<td> <%= Item.find(bill.item_id).title %></td>
					<td><%= bill.gross %></td>
					<td><%= bill.tear %></td>
					<td><%= bill.gross - bill.tear %></td>
					<td><%= bill.price %></td>
					<td><%= ((bill.gross - bill.tear) * bill.price).round(1) %></td>
				</tr>
			<% end %>
			
		</tbody>

	</table>
</div>

app/views/sales/customer.html.erb
<script type="text/javascript">
  var d = document.getElementById("customers");
d.className = d.className + " active";
  $(document).ready(function() {

    var table = $('#example').dataTable({
        "order": [[1, "desc"]],
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard"
                },
                {
                    "sExtends": "csv",
                    "sButtonText": "Save to CSV"
                }
            ]
        },
        /////////////////////////////////////////////
        <% if @invoices.count > 0 %>
           "footerCallback": function ( row, data, start, end, display ) {
              var api = this.api(), data;
   
              // Remove the formatting to get integer data for summation
              var intVal = function ( i ) {
                  return typeof i === 'string' ?
                      i.replace(/[\$,]/g, '')*1 :
                      typeof i === 'number' ?
                          i : 0;
              };
   
              // Total over all pages
              total = api
                  .column( 2 )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  } );
              $('#totalamount').text('Total Cash: '+total);

              // Total over this page
              pageTotal = api
                  .column( 2, { page: 'current'} )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  }, 0 );
   
              // Update footer
              $('#pgamount').text('Total: '+ pageTotal);

          }
        <% end %>

    /////////////////////////////////////////
    });
  });

</script>

<h2><%= @customer.name %>
<div style = "float: right;font-size: 14px;border-radius: 10px;padding: 5px;background-color: white;margin-bottom:10px;">
  <strong> <span id = 'totalamount' style = "color: Blue;margin-right : 40px; margin-left: 20px;">  Total : 0 </span></strong>
</div>
</h2>
<table id="example" class="display">
  <thead>
    <tr>
      <th>Date</th>
      <th>Invoice #</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.try(:each) do |inv| %>
      <tr class ="<%= inv.id %>">
        <td>
          <%= inv.created_at.strftime('%a, %B %e, %Y') %>
        </td>
        <td>
          <%= link_to inv.id, credit_invoice_path(inv.id) %>
        </td>
        <td>
          <%= (inv.bills.sum("(gross-tear) * price")).round(1) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style = "float:right; font-size: 14px">
  <strong> <span id = 'pgamount' > </span></strong><br>
  <strong> <span id = 'pgCash' > </span></strong><br>
  <strong> <span id = 'pgCredit' > </span></strong>
</div>
<script>
  $('#cancelbtn').on('click',function(){
    $('.'+$(this).attr("name")).remove() ;
  });

</script>

app/views/sales/index.html.erb
<script type="text/javascript">
  var d = document.getElementById("saless");
d.className = d.className + " active";
  $(document).ready(function() {

    var table = $('#example').dataTable({
        "order": [[1, "desc"]],
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "//cdn.datatables.net/tabletools/2.1.5/swf/copy_csv_xls_pdf.swf",
            "aButtons": [
                {
                    "sExtends": "copy",
                    "sButtonText": "Copy to clipboard"
                },
                {
                    "sExtends": "csv",
                    "sButtonText": "Save to CSV"
                }
            ]
        },
        /////////////////////////////////////////////
        <% if @invoices.count > 0 %>
           "footerCallback": function ( row, data, start, end, display ) {
              var api = this.api(), data;
   
              // Remove the formatting to get integer data for summation
              var intVal = function ( i ) {
                  return typeof i === 'string' ?
                      i.replace(/[\$,]/g, '')*1 :
                      typeof i === 'number' ?
                          i : 0;
              };
   
              // Total over all pages
              total = api
                  .column( 3 )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  } );
              $('#totalamount').text('Total: '+total);

              // Total over this page
              pageTotal = api
                  .column( 3, { page: 'current'} )
                  .data()
                  .reduce( function (a, b) {
                      return intVal(a) + intVal(b);
                  }, 0 );
   
              // Update footer
              $('#pgamount').text('Total: '+ pageTotal);
          }
        <% end %>
    });
  });

</script>

<h2>Invoices
<a href="<%= new_sale_path %>" class="btn btn-info pull-right" style="width:200px;">Create Sale</a> <br>
<div style = "float: right;font-size: 14px;border-radius: 10px;padding: 5px;width:200px; background-color: white;margin-bottom:10px;">

  <strong> <span id = 'totalamount' style = "color: Blue;margin-right : 40px; margin-left: 20px;">  Total : 0 </span></strong>
</div>
</h2>
<table id="example" class="display">
  <thead>
    <tr>
      <th>Date</th>
      <th>Invoice ID</th>
      <th>Customer/Party Name</th>
      <th>Total</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.try(:each) do |inv| %>
      <tr class ="<%= inv.id %>">
        <td>
          <%= inv.created_at.strftime('%a, %B %e, %Y') %>
        </td>
        <td>
          <%= link_to inv.id, credit_sale_path(inv.id) %>
        </td>
        <td>
          <%= inv.customerName %>
        </td>
        <td>
          <%= inv.lines.sum("(gross-tear) * price") %>
        </td>
        <td>
          <%= link_to 'Delete', sale_path(inv.id), :method => :delete %>
          <%= link_to 'Edit', edit_line_path(inv.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div style = "float:right; font-size: 14px">
  <strong> <span id = 'pgamount' > </span></strong><br>
  <strong> <span id = 'pgCash' > </span></strong><br>
  <strong> <span id = 'pgCredit' > </span></strong>
</div>
<script>
  $('#cancelbtn').on('click',function(){
    $('.'+$(this).attr("name")).remove() ;
  });

</script>

app/views/sales/new.html.erb
<script type="text/javascript">
  var d = document.getElementById("saless");
d.className = d.className + " active";
</script>


<%= form_for @invoice, url: updateInvoice_sales_path(@autogen), methoed: :post do |inv| %>
	<h2>Sales Invoice</h2>
	<br>
	<div class="form-group " style=" float:right; margin-right: 242px;">
		<label>Date </label>
		<%= inv.text_field :created_at, id: 'datepicker' , :style => 'width:70%;height:34px;', class: 'form-control',  required: true, autofocus: true %>
	</div>
	<br><br><br><br>
	<div class="col-md-6">
		<div class="form-group">
			<label>invoice ID</label>
			<input style = 'width:70%;height:34px;'  class = 'form-control' value = '<%=@autogen%>' disabled >
		</div>

		<div class="form-group">
			<label>Driver</label>
			<%= inv.text_field :driver , :style => 'width:70%;height:34px;', class: 'form-control', required: true, autofocus: true %>
		</div>

	</div>
	<div class="col-md-6">

		<div class="form-group">
			<label> Company/Party  </label>
			<%= inv.collection_select :customer_id, Customer.where.not(status: 'delete').order(:name),:id,:name , {}, {class: "form-control", style: 'width:70%;'} %>
			<div>
				<span id = "credits" style = "color: red">Credit: <%= @credit %></span>
			</div>
			
		</div>
		
		<div class="form-group">
			<label>Vehicle #</label>
			<%= inv.text_field :vehicle, :style => 'width:70%;height:34px;', class: 'form-control' %>
		</div>
		
		<!-- <div class="size-bock">
			<%#= inv.submit "Create Invoice", :class => 'btn-create btn btn-success' %>
		</div> -->
	</div>
<% end %>
<div class = "col-md-12" style="background-color:black; margin-bottom:20px;margin-top:20px;">	
</div>
<div class = "billform">
<!-- /////////////////////items form for//////////////////////////// -->
	<%= form_for @bill, url: createBill_lines_path, methoed: :post,remote: true do |bill| %>
		<div class="row">
			<%= bill.hidden_field :sale_id, :value => @autogen %>
	    	<div class="col-md-3">
	    		<div class="form-group">
					<label>Qualtiy Name</label>
					<%= bill.collection_select :item_id, Item.where.not(status: 'delete').order(:title),:id,:title , {}, {class: "form-control", style: 'width:100%;height:34px;', id: 'item_code'} %>
				</div>
	    	</div>

	   		<div class="col-md-3">
	   			<div class="form-group">
					<label>Gross Weight (Kg)</label>
					<%= bill.text_field :gross, :id => 'quantity', :style => 'width:100%;height:34px;', class: 'form-control', required: true %>
				</div>
			</div>

			<div class="col-md-3">
	   			<div class="form-group">
					<label>Tear Weight (Kg)</label>
					<%= bill.text_field :tear, :style => 'width:100%;height:34px;', class: 'form-control', required: true %>
				</div>
			</div>

	    	<div class="col-md-3">
	    		<div class="form-group">
					<label>Rate</label>
					<%= bill.text_field :price, :style => 'width:100%;height:34px;', class: 'form-control', required: true %>
				</div>
			</div>
		</div>
		
		<div class="form-group">
			<span onclick="abc()"><%= bill.submit "Add Item", :id => "billbutton", :class => 'btn btn-block btn-info form-control', :style => 'width:31%; float:right;' %></span>
		</div>

	<% end %>
</div>

<div style="padding:10px;border-radius:5px;background-color:white;margin-top:60px;">
	<table class="table">
		<thead>
			<th>Quality Name</th>
			<th>Gross Weight(Kg)</th>
			<th>Tear Weight (Kg)</th>
			<th>Net Weight</th>
			<th>Rate</th>
			<th>Total</th>
			<th></th>
		</thead>
		<tbody id = 'billtable'>
			
		</tbody>

	</table>
</div>
<br>

<div class="" >
	<label style = 'float:right; margin-right:22%;'>Total Amount</label>
	<br>
	<br>
	<input style = 'float:right; width:31%;' id = "totalfield" class = 'form-control' placeholder = '0' disabled>
	<br>
	<br>
	<input type="button" id = "submit" style="float:right; width:31%"; class = "btn-create btn btn-success" value = 'Create Invoice'>
</div>



<script type="text/javascript">
	function abc(){
		setTimeout(
			function(){
				$.get('/lines/getbills', {id: $('#item_code').val()})
	       			.done(function(data){
	       				$('#billtable').html('');
	       				$('#totalfield').val(data[0].totalSum.toFixed(1));
	       				data[0].b.forEach(function(bill){
	       					var elem = document.createElement("input");
	       					elem.type = "button";
	       					elem.value = "Remove";
	       					elem.className = 'btn btn-danger';
	       					elem.setAttribute("id", bill.id);
	       					elem.onclick = function(){
	       						$.get('/lines/removebills', {id: this.id})
	       							.done(function(data){
	       								var v = Math.round((data[0].total));
	       								console.log(v);
	       								$('#totalfield').val(v);
	       								$('.'+data[0].id).remove();
	       								// var el = document.getElementByClassName(data[0].id);
	       								// el.parentNode.removeChild(el);
	       							})
	       					};
	       					var tr = document.createElement("tr");
	       					tr.className = ''+bill.id;
	       					var td1 = document.createElement("td");
	       					var td2 = document.createElement("td");
	       					var td3 = document.createElement("td");
	       					var td4 = document.createElement("td");
	       					var td5 = document.createElement("td");
	       					var td6 = document.createElement("td");
	       					var td7 = document.createElement("td");

	       					td1.innerHTML = bill.item_title;
	       					td2.innerHTML = bill.gross;
	       					td3.innerHTML = bill.tear;
	       					td4.innerHTML = bill.gross - bill.tear;
	       					
	       					td5.innerHTML = bill.price;
	       					td6.innerHTML = ((bill.gross - bill.tear)* bill.price).toFixed(1);
	       					td7.appendChild(elem);
	       					tr.appendChild(td1);
	       					tr.appendChild(td6);
	       					tr.appendChild(td2);
	       					tr.appendChild(td3);
	       					tr.appendChild(td4);
	       					tr.appendChild(td5);
	       					tr.appendChild(td6);
	       					tr.appendChild(td7);
	       					$('#billtable').append(tr);
	       					// $('#billtable').append('<tr><td>'+ bill.item_title +'</td><td>'+bill.quantity+'</td><td>'+bill.price+'</td><td>'+bill.quantity*bill.price+'</td> <td>'+elem+'</td></tr>');
	       				});
	       			})
				$('#new_line').closest('form').find("input[type=text], textarea").val("");
			}
		,1000);	
	}

	$("#paidamount").on('keyup',function(){
		$('#credit').val($('#totalfield').val() - $('#paidamount').val()); 
	});

	$("#submit").on('click',function(){
		$('#new_sale').submit();
	});
	$( "#sale_customer_id" ).change(function() {
	  $.get('/invoices/getCredit', {id: $('#sale_customer_id').val()})
	    .done(function(data){
	    	$('#credits').text('Credit: '+ data[0].credit)
	    });
	});
	$("#datepicker").datepicker({format: 'yyyy-mm-dd'} );

</script>